apiVersion: v1
kind: ConfigMap
metadata:
    namespace: flux-system
    name: cluster-settings
data:
    TIMEZONE: America/New_York
    #
    SVC_MOSQUITTO_ADDR: 192.168.69.110
    SVC_HOME_ASSISTANT_ADDR: 192.168.69.103
    SVC_PLEX_ADDR: 192.168.69.104
    SVC_QBITTORRENT_ADDR: 192.168.69.106
    SVC_SYSLOG_ADDR: 192.168.69.111
    SVC_NGINX_ADDR: 192.168.69.101
